twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        project_name: '%env(PROJECT_NAME)%'
        allCategories: '@App\Twig\Extension\CategoryExtension'


when@test:
    twig:
        strict_variables: true
